import hre from "hardhat";
import fs from "fs";
import path from "path";
const { ethers, network } = hre;

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying AegisDAO ecosystem with account:", deployer.address);
  console.log("Network:", network.name);

  // 1. Deploy AegisToken
  const AegisToken = await ethers.getContractFactory("AegisToken");
  const token = await AegisToken.deploy(deployer.address);
  await token.waitForDeployment();
  const tokenAddress = await token.getAddress();
  console.log("AegisToken deployed to:", tokenAddress);

  // 2. Deploy AegisTimelock
  const minDelay = 60; // 60 seconds delay for testnet/dev
  const proposers: string[] = [];
  const executors: string[] = [ethers.ZeroAddress]; // Anyone can execute when ready
  const admin = deployer.address;

  const AegisTimelock = await ethers.getContractFactory("AegisTimelock");
  const timelock = await AegisTimelock.deploy(minDelay, proposers, executors, admin);
  await timelock.waitForDeployment();
  const timelockAddress = await timelock.getAddress();
  console.log("AegisTimelock deployed to:", timelockAddress);

  // 3. Deploy AegisGovernor
  const votingDelay = 1; // 1 block
  const votingPeriod = 50; // ~50 blocks
  const proposalThreshold = ethers.parseEther("100"); // 100 AGIS needed to propose
  const quorumPercentage = 4; // 4%

  const AegisGovernor = await ethers.getContractFactory("AegisGovernor");
  const governor = await AegisGovernor.deploy(
    tokenAddress,
    timelockAddress,
    votingDelay,
    votingPeriod,
    proposalThreshold,
    quorumPercentage,
    deployer.address // Use deployer as the Oracle for the testnet deployment
  );
  await governor.waitForDeployment();
  const governorAddress = await governor.getAddress();
  console.log("AegisGovernor deployed to:", governorAddress);

  // 4. Deploy AegisTreasury
  const AegisTreasury = await ethers.getContractFactory("AegisTreasury");
  const treasury = await AegisTreasury.deploy(timelockAddress);
  await treasury.waitForDeployment();
  const treasuryAddress = await treasury.getAddress();
  console.log("AegisTreasury deployed to:", treasuryAddress);

  // 5. Setup Timelock Roles
  const PROPOSER_ROLE = await timelock.PROPOSER_ROLE();
  const EXECUTOR_ROLE = await timelock.EXECUTOR_ROLE();
  const TIMELOCK_ADMIN_ROLE = await timelock.DEFAULT_ADMIN_ROLE();

  await timelock.grantRole(PROPOSER_ROLE, governorAddress);
  await timelock.grantRole(EXECUTOR_ROLE, ethers.ZeroAddress);
  await timelock.revokeRole(TIMELOCK_ADMIN_ROLE, deployer.address);
  console.log("Timelock roles configured successfully.");

  // 6. Write deployed addresses to .env.local and lib/config.ts
  const rootDir = path.resolve(__dirname, "..");
  const envLocalPath = path.join(rootDir, ".env.local");
  const chainKey = network.name === "amoy" ? "amoy" : "sepolia";

  // Append/update .env.local
  const envEntries = [
    `NEXT_PUBLIC_AEGIS_TOKEN_ADDRESS=${tokenAddress}`,
    `NEXT_PUBLIC_AEGIS_GOVERNOR_ADDRESS=${governorAddress}`,
  ];

  let envContent = "";
  if (fs.existsSync(envLocalPath)) {
    envContent = fs.readFileSync(envLocalPath, "utf8");
    // Remove old entries
    envContent = envContent
      .split("\n")
      .filter(line => !line.startsWith("NEXT_PUBLIC_AEGIS_TOKEN_ADDRESS") && !line.startsWith("NEXT_PUBLIC_AEGIS_GOVERNOR_ADDRESS"))
      .join("\n");
  }
  envContent += "\n" + envEntries.join("\n") + "\n";
  fs.writeFileSync(envLocalPath, envContent.trim() + "\n");
  console.log("\n.env.local updated with deployed contract addresses.");

  // Print generated config snippet for lib/config.ts
  const configSnippet = `
  // ─── Generated by deploy.ts on ${new Date().toISOString()} ───
  ${chainKey}: {
    token: "${tokenAddress}",
    governor: "${governorAddress}",
    timelock: "${timelockAddress}",
    treasury: "${treasuryAddress}",
  },`;

  console.log("\n--- Deployment Summary ---");
  console.log(`Token:     ${tokenAddress}`);
  console.log(`Timelock:  ${timelockAddress}`);
  console.log(`Governor:  ${governorAddress}`);
  console.log(`Treasury:  ${treasuryAddress}`);
  console.log(`\nUpdate CONTRACT_ADDRESSES in lib/config.ts:\n${configSnippet}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
